005 gui
maxkvant/JavaHomeWork2 pull request #4
Opened 2017-05-03 20:59 UTC by maxkvant

2017-05-27 09:29 UTC, yurii-litvinov requested changes
- Надо ещё дать клиенту возможность подключаться к удалённому серверу, для этого надо дать возможность указать ip-адрес (и порт, но порт можно и захардкодить)
- Ходить по папкам вверх неудобно
- Форму можно сжать до упора, нехорошо
На момент дедлайна качать файлы было, кажется, нельзя.

2017-05-27 09:29 UTC, yurii-litvinov commented on 004-Server/src/main/java/Main.java
> +public class Main extends Application {
Тоже нужен комментарий

2017-05-27 09:29 UTC, yurii-litvinov commented on 004-Server/src/main/java/Main.java
> +
Лишняя пустая строка

2017-05-27 09:29 UTC, yurii-litvinov commented on 004-Server/src/main/java/Main.java
> +        };
Обработчик с нетривиальной логикой имело бы смысл сделать отдельным методом

2017-05-27 09:29 UTC, yurii-litvinov commented on 004-Server/src/main/java/Main.java
> +    }
Такие большие методы --- это плохо, ухудшается читаемость

2017-05-27 09:29 UTC, yurii-litvinov commented on 004-Server/src/main/java/Main.java
> +                new Server().start();
Запускать в одном приложении и клиент, и сервер --- это странно, FTP полезен, когда сервер на одном компе, а клиент на другом

2017-06-04 14:23 UTC, yurii-litvinov approved these changes
Всё равно если запустить два приложения и в одном из них стартовать сервер, из второго подключиться не удаётся. Но ладно, остальные замечания исправлены, так что зачтена.

2017-06-04 14:46 UTC, maxkvant commented
Если захардкодить порт, то работает.

2017-06-04 14:54 UTC, merged